apiVersion: v1
kind: PersistentVolume
metadata:
  name: hybrid-qdrant-snapshots-1-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/hybrid-qdrant-snapshots-1"
